# -*- coding: utf-8 -*-
"""bootcampproject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N4O-h9rjk_ZCBtzk4RdU6Bwxb_wGm6fK
"""

## MADE BY Harshit Himanshu
## EMAIL -- official0harshit6himanshu@gmail.com
##***************************************************************************************************
## PYTHON AND DEEP LEARNING BOOTCAMP

##***************************************************************************************************

## improting dataset
from sklearn.datasets import load_breast_cancer
Data = load_breast_cancer()

print (Data.DESCR)

features = Data.data
target = Data.target 
print(features.shape)
print(target.shape)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.2)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(32, input_dim = 30, activation='relu')) ##hidden layer 1
model.add(Dense(64, activation='relu')) ##hidden layer 2
model.add(Dense(1, activation='sigmoid'))

model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()

model.fit(x_train, y_train, epochs=10000)

scores = model.evaluate(x_test, y_test)
print(scores)

predictions = model.predict(x_test)
label = []
for pred in predictions:
  if pred>=0.5:
    print("Malignent")
  else:
    print("Benign")